-- v54_suscripcion_status.sql
-- NO APLICAR: la suscripción se lee directamente de tenants.fecha_vencimiento
-- (actualizada por superadmin.html al registrar un pago vía salon_admin_registrar_pago).
-- No existe tabla suscripciones_negocio ni planes_salon en este schema.
-- El campo fecha_vencimiento en tenants fue añadido por v50_pagos_plataforma.sql.
